configfile: "config.yaml"

report: "report/workflow.rst"

include: "rules/utils.smk"

input_list = get_input()

include: "rules/process_fastq.smk"
include: "rules/index_reference_genome.smk"
include: "rules/map_reads.smk"

rule all:
    input:
        rules.index_ref.output,
        rules.index_mapped_reads.output
